#!/bin/sh
#This file is called submit-script.sh
#SBATCH --time=01:00:00        # run time in days-hh:mm:ss (1 hours)
#SBATCH --nodes=4              # require 4 nodes
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16     # cpus per node (16 tasks per node = 64 total)
#SBATCH --error=job.%J.err
#SBATCH --output=job.%J.out
#SBATCH --job-name=HPL_Honda

cd ~/hpl/bin/Task5/

module load openmpi/5.0.7-gcc-14.2.0
module load openBLAS/0.3.28-SANDYBRIDGE-vectorized-gcc-14.2.0-openmpi-5.0.7

# CRITICAL FIX: Stop OpenBLAS from spawning too many threads
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

mpirun -np 4 ./xhpl
