#!/bin/sh
#This file is called submit-script.sh
#SBATCH --time=01:00:00        # run time in days-hh:mm:ss (1 hours)
#SBATCH --nodes=4              # require 4 nodes
#SBATCH --ntasks-per-node=16   # cpus per node (16 tasks per node = 64 total)
#SBATCH --error=job.%J.err
#SBATCH --output=job.%J.out
#SBATCH --job-name=HPL_Honda

cd ~/hpl/bin/Task5/

export PATH=${HOME}/opt/openmpi/bin:${PATH}
export LD_LIBRARY_PATH=${HOME}/opt/openmpi/lib:/home/software/beegfs/openblas/0.3.28/openmpi-5.0.10-gcc-15.2.0-SANDYBRIDGE-vectorized/lib:${LD_LIBRARY_PATH}

# CRITICAL FIX: Stop OpenBLAS from spawning too many threads
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

mpirun -np 64 ./xhpl
